"""Core module for the University Recommendation System."""

from .circuit_breaker import (
    CircuitBreaker,
    CircuitBreakerConfig,
    CircuitBreakerRegistry,
    CircuitState,
    get_circuit_breaker,
)
from .config import Settings, get_settings, reload_settings
from .constants import (
    APPLICATION_DEADLINES,
    CURRENCY_CODES,
    DEGREE_TYPES,
    EXPORT_CONFIGS,
    LANGUAGE_REQUIREMENTS,
    LLM_PROMPTS,
    PROGRAM_SPECIALIZATIONS,
    QUALITY_THRESHOLDS,
    UNIVERSITY_METADATA,
    UNIVERSITY_URLS,
)
from .exceptions import (
    APIError,
    BaseError,
    CacheError,
    CircuitBreakerError,
    ConfigurationError,
    ConnectionError,
    DatabaseError,
    DeepSeekAPIError,
    DuplicateDataError,
    ErrorCategory,
    ErrorContext,
    ErrorSeverity,
    ExportError,
    FileOperationError,
    GroqAPIError,
    LLMExtractionError,
    NetworkError,
    QualityCheckError,
    QueryError,
    RateLimitError,
    ScrapingError,
    TimeoutError,
    UniversityScraperError,
    ValidationError,
)
from .retry import (
    CircuitBreakerRetry,
    ExponentialBackoffRetry,
    RetryConfig,
    RetryPolicy,
    RetryStrategy,
    retry_with_backoff,
)

__all__ = [
    # Configuration
    "Settings",
    "get_settings",
    "reload_settings",
    # Constants
    "UNIVERSITY_URLS",
    "UNIVERSITY_METADATA",
    "DEGREE_TYPES",
    "PROGRAM_SPECIALIZATIONS",
    "LANGUAGE_REQUIREMENTS",
    "CURRENCY_CODES",
    "APPLICATION_DEADLINES",
    "QUALITY_THRESHOLDS",
    "EXPORT_CONFIGS",
    "LLM_PROMPTS",
    # Enhanced Exceptions
    "BaseError",
    "ErrorSeverity",
    "ErrorCategory",
    "ErrorContext",
    "UniversityScraperError",
    "ScrapingError",
    "LLMExtractionError",
    "ValidationError",
    "DatabaseError",
    "ConnectionError",
    "DuplicateDataError",
    "QueryError",
    "ConfigurationError",
    "APIError",
    "GroqAPIError",
    "DeepSeekAPIError",
    "RateLimitError",
    "NetworkError",
    "TimeoutError",
    "ExportError",
    "FileOperationError",
    "QualityCheckError",
    "CacheError",
    "CircuitBreakerError",
    # Retry Framework
    "RetryStrategy",
    "RetryConfig",
    "RetryPolicy",
    "ExponentialBackoffRetry",
    "CircuitBreakerRetry",
    "retry_with_backoff",
    # Circuit Breaker
    "CircuitState",
    "CircuitBreakerConfig",
    "CircuitBreaker",
    "CircuitBreakerRegistry",
    "get_circuit_breaker",
]
